# Generated by Django 2.2.4 on 2022-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='upladed_by',
        ),
        migrations.AddField(
            model_name='book',
            name='user_favs',
            field=models.ManyToManyField(blank=True, related_name='fav_book', to='app_one.User'),
        ),
    ]
